<?php


namespace Packages\Country\tests\Unit;


use Illuminate\Foundation\Testing\DatabaseMigrations;
use Packages\Country\App\Models\Country;
use Packages\Country\App\Models\Tax;
use Tests\TestCase;

class TaxTest extends TestCase {

    use DatabaseMigrations;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->tax = Tax::factory()->create();
    }

    /** @test */
    public function it_belongs_to_a_a_country()
    {
        $this->assertInstanceOf(Country::class, $this->tax->taxable);
    }

    /** @test */
    public function as_a_percentage()
    {
        $this->assertIsFloat($this->tax->percentage);
    }

}
