<?php

namespace Packages\Orders\tests\Unit;

use App\Models\Setting;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Packages\Orders\App\Models\InvoiceProvider;
use Packages\Orders\App\Providers\Invoice\InvoiceExpress\InvoiceExpress;
use Packages\Orders\App\Providers\Invoice\Moloni\Moloni;
use Tests\TestCase;

class InvoiceProviderTest extends TestCase {
    use DatabaseMigrations;

    public $payemnt_methods;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        Setting::create(['name' => 'invoice_providers', 'data' => [
            ['provider' => Moloni::class, 'key' => 'moloni_key', 'private_key' => 'moloni_private_key'],
            ['provider' => InvoiceExpress::class, 'key' => 'invoice_express_key', 'private_key' => 'invoice_express_private_key']
        ]]);
    }

    /** @test */
    public function its_possible_to_get_the_provider_details()
    {
        $moloni_credencials = (new InvoiceProvider())->getDataProvider(Moloni::class);

        $this->assertEquals(['key'=>'moloni_key', 'private_key' => 'moloni_private_key'], $moloni_credencials);

        $invoice_express_credencials = (new InvoiceProvider())->getDataProvider(InvoiceExpress::class);
        $this->assertEquals(['key'=>'invoice_express_key', 'private_key' => 'invoice_express_private_key'], $invoice_express_credencials);

    }
}
