<?php


namespace Packages\Reserved\tests\Feature;


use App\Models\Page;
use App\Models\Seo;
use App\Models\User;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Support\Facades\Hash;
use Packages\Reserved\App\Models\ReservedArea;
use Tests\TestCase;

class PageTest extends TestCase {

    use DatabaseMigrations;
    public $reserved;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->reserved = ReservedArea::factory()->create(['prefix'=>'prefix_test']);
        $this->actingAs(User::factory()->create(['reserved_area_id'=>$this->reserved->id]));
    }


    /** @test */
    public function a_authenticaded_user_can_access_to_the_reserved_area()
    {
        $this->withoutExceptionHandling();
        $page = Page::factory()->create(['pageable_id'=>$this->reserved->id, 'pageable_type'=>ReservedArea::class]);
        Seo::factory()->create(['seoable_id'=>$page->id, 'seoable_type'=>Page::class]);
        $response = $this->get($this->reserved->prefix.'/'.$page->slug);

        $response->assertStatus(200);

    }


}
